### ISSUE TITLE
Unhandled Rejection createApp

### ISSUE THREAD

**Issue by mattvb91** [corejam/corejam#144]
```
npx @corejam/cli createApp site
⠋ Creating new Corejam application: siteUnhandled Rejection at: Promise Promise {
  <rejected> Error: Path to move doesn't exist ./site/gitignore
      at generateSourceDoesntExistError (@corejam/cli/node_modules/fs-jetpack/lib/move.js:32:15)
      at @corejam/cli/node_modules/fs-jetpack/lib/move.js:137:28 {
    code: 'ENOENT'
  }
```

Seems to be caused by https://github.com/corejam/corejam/blob/9253c9961ce25140fb90971aff27a0d1f3ad8363/packages/cli/src/commands/generateApp.ts#L22

Not sure why this doesnt happen in build process?

Also when running `yarn dev`

```
[ ERROR ]  Error: Cannot find module '@corejam/run/dist/index.html' Require stack: -
           /stencil.config.ts -
           /node_modules/@stencil/core/compiler/stencil.js -
```

`@corejam/run/dist/index.html` doesnt seem to be in the run/dist

**Comment by mattvb91** [comment]
I think we need to make a test with all the "linked" packages but then also have 1 test where only "cli" is linked and all other packages in the test are pulled from NPM to createApp? @patrickhaug what do you think?

**Comment by patrickhaug** [comment]
Gitignore should be fixed. Missing html is probably due to releasing without correct prepublish hook - copy html. we could release new versions
