### ISSUE TITLE
Nextjs Example: Missing dependencies

### ISSUE THREAD

**Issue by rotpunkt-dev** [corejam/corejam#328]
### Problem

The nextjs example does not have the required dependencies and fails.
I tried the "next" and "master" branch.

### Steps
`$ cd examples/nextjs`
`$ yarn`
`$ yarn dev`

### Output
>yarn run v1.22.4
$ next dev
ready - started server on http://localhost:3000
error - ./components/Layout.js:1:0
Module not found: Can't resolve '@corejam/core-components/react'
 1 | import { CorejamUiBase } from "@corejam/core-components/react";
  2 | import { DershopHeader, DershopFooter } from "@corejam/plugin-dershop/react";
  3 | 
  4 | const Layout = ({ children }) => {`

**Comment by mattvb91** [comment]
I think whats happening is that because of it being run inside the lerna mono repo structure it has not yet hoisted the `@corejam/*` plugins. 

Can you go to the project root and run `yarn bs && yarn build` and try it again? I will add it to the readme too.

**Comment by patrickhaug** [comment]
Another approach could be to remove examples from lerna tracking, so examples bootstrap from npm without local symlinks.

**Comment by rotpunkt-dev** [comment]
Yes, `yarn bs && yarn build` fixed the issue. Might be a good idea to decouple the examples from the local symlinks.

**Comment by patrickhaug** [comment]
#330 should fix this for new clones. we have all the packages on npm now. we can still link local during development to test things out in examples
