### ISSUE TITLE
Errors on latest release

### ISSUE THREAD

**Issue by mattvb91** [corejam/corejam#395]
Latest master release has following errors: 

```
Uncaught (in promise) TypeError: Failed to resolve module specifier "autoprefixer". Relative references must start with either "/", "./", or "../".
```
```
TypeError: Failed to resolve module specifier "crypto-hash". Relative references must start with either "/", "./", or "../".
```

I think the crypto-hash error was introduced due to upgrading to hashed queries in apollo client. Not sure about autoprefixer

**Comment by patrickhaug** [comment]
Stencil config template changed. This is the reason for this bug, should be manually patched, and should more prominent in information *what* to do during upgrade .. sorry

Stencil config needs - until we export our own stencil config: 
`import nodePolyfills from "rollup-plugin-node-polyfills";`
and
`const config: Config = {
  ..
  rollupPlugins: {
    after: [nodePolyfills()],
  },
};`

**Comment by mattvb91** [comment]
@patrickhaug I think we need to adjust the CLI template to close this then?

**Comment by patrickhaug** [comment]
#398  has updated config

**Comment by mattvb91** [comment]
This is still open. Relates to #399
