### ISSUE TITLE
Corejam/base make bundle

### ISSUE THREAD

**Issue by patrickhaug** [corejam/corejam#62]
We need to really bundle corejam/base, preferable with rollup. Let's keep track, what is important for server only and what should work in browser env. Awesome sauce would be rollup generating all needed filed adhoc and let them access from anywhere via http.

@mattvb91 please chime in for seperating concerns here.

**Comment by mattvb91** [comment]
I think as it stands currently because we have removed the Browser client out of the package it means it is all server only at the moment? Unless im missing something
